// <auto-generated />
namespace CEAG.ACESSODADOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AlteraDebito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteraDebito));
        
        string IMigrationMetadata.Id
        {
            get { return "202011250104308_AlteraDebito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
