// <auto-generated />
namespace CEAG.ACESSODADOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CamposTaxa1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposTaxa1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007180614396_CamposTaxa1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
